### ISSUE TITLE
[EPIC]: INIT PROJECT

### ISSUE THREAD

**Issue by millehorde** [Juliette13/nestjs-project-blog#1]
_From @millehorde on January 11, 2019 0:14_

_Copied from original issue: millehorde/BlogSpec#58_

**Comment by millehorde** [comment]
This issue was moved to timAdrien/blog-api-nestJS#1

**Comment by millehorde** [comment]
This issue was moved to paullbr/Nest-api-blog#1

**Comment by millehorde** [comment]
This issue was moved to sorasful/blog-api#1

**Comment by millehorde** [comment]
This issue was moved to Jowkitozz/BlogTest#1

**Comment by Juliette13** [comment]
Ready to dev !
